# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetaChatDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AgoraSDK', :path => 'sdk'
  pod 'Zip'
  pod 'SnapKit'
  pod 'Masonry'
  pod 'JXSegmentedView'
  pod 'SDWebImage'
#  pod 'IQKeyboardManager'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SwiftyMenu', '~> 0.6.3'
  # Pods for MetaChatDemo
#  pod 'libyuv-iOS', '~> 1.0.2'

end
