# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetaChatDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AgoraSDK', :path => 'sdk'
  pod 'Zip'
  pod 'SnapKit'
  pod 'Masonry'
  pod 'JXSegmentedView'
  pod 'SDWebImage','5.12.6'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'HyphenateChat','3.9.5'
  pod 'MJRefresh'
end
